FROM confluentinc/cp-kafka-connect

COPY ./lib/jcustenborder-kafka-connect-spooldir-1.0.41 /usr/share/confluent-hub-components
COPY ./lib/confluentinc-kafka-connect-jdbc-5.4.0-beta1 /usr/share/confluent-hub-components
